# Generated by Django 4.0.6 on 2022-07-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
